name: Deploy to Linode

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Smoketest
      - name: Build the wiki
        run: docker-compose up -d
      - name: Test container comes up and listens on port 8000
        run: docker run --network container:wiki_wiki_1 curlimages/curl -s --retry 10 --retry-connrefused http://localhost:8000/
      
      # Build
      - name: Pull latest changes on Linode node
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.WIKI_HOST }}
            USERNAME: ${{ secrets.WIKI_DEPLOY_USER }}
            PORT: ${{ secrets.WIKI_SSH_PORT }}
            KEY: ${{ secrets.SSHKEY }}
            script: cd ${{ secrets.PROJECT_PATH }} && git fetch && git checkout master && git pull
      - name: Build
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.WIKI_HOST }}
            USERNAME: ${{ secrets.WIKI_DEPLOY_USER }}
            PORT: ${{ secrets.WIKI_SSH_PORT }}
            KEY: ${{ secrets.SSHKEY }}
            script: cd ${{ secrets.PROJECT_PATH }} && docker-compose run wiki build

      # Deploy
      - name: Deploy new image and cleanup
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.WIKI_HOST }}
            USERNAME: ${{ secrets.WIKI_DEPLOY_USER }}
            PORT: ${{ secrets.WIKI_SSH_PORT }}
            KEY: ${{ secrets.SSHKEY }}
            script: docker-compose -f ~/docker-compose.yml up -d && docker image prune -af