name: Test

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build containers
      run: docker-compose build

    - name: Build site
      run: docker-compose run wiki build --verbose --strict

    - name: Build production container
      run: docker build -f prod/Dockerfile .
